[pytest]
pythonpath = .
norecursedirs = .git .venv __pycache__
log_cli_level = INFO

markers =
    integration: marks tests that require external services or full system integration (deselect with '-m "not integration"')
    unit: marks tests that can be run in isolation without external dependencies (run with '-m unit')
    order: mark test to run in a specific order

addopts = --strict-markers -v

testpaths = tests
